name: 'Deploy'

on:
  release:
    types:
      - published
  push:
    branches:
      - dev
      - qa
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'Deploy app & run sanity tests'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: amondnet/vercel-action@v20

        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          alias-domains: |
            dnb-stack.vercel.app

      - run: yarn
      - run: yarn cypress:run
# {{BRANCH}}.myapp.com - for deploying to different envs via branches
